spring:
  config:
    activate:
      on-profile: local

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    oauth:
      client-id: ${KEYCLOAK_WEB_CLIENT_ID:aegis-web}
      use-pkce-with-authorization-code-grant: true
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html

aegis:
  app:
    base-url: ${AEGIS_APP_BASE_URL:http://localhost:5173}
